### ISSUE TITLE
npx @shopware-pwa/cli init fails because of TypeError: Cannot set property 'lint' of undefined

### ISSUE THREAD

**Issue by thmsnhl** [DivanteLtd/shopware-pwa#1164] opened 2020-10-07 06:43 UTC
### Describe the bug

When running `npx @shopware-pwa/cli init` I cannot complete the initialization process because of a type error.

### Steps to reproduce
- Run `npx @shopware-pwa/cli init` 
- Paste Shopware instance credentials
- Select `latest stable (recommended)`
```
Which version you'd like to use: · latest stable (recommended)
✔ Preparing Nuxt project
⠦ Updating configuration for option: latest stable (recommended)/Users/thomasnohl/.npm/_npx/7892/lib/node_modules/@shopware-pwa/cli/node_modules/gluegun/build/index.js:13
    throw up;
    ^

TypeError: Cannot set property 'lint' of undefined
    at /Users/thomasnohl/.npm/_npx/7892/lib/node_modules/@shopware-pwa/cli/build/extensions/nuxt-extension.js:164:49
    at Object.<anonymous> (/Users/thomasnohl/.npm/_npx/7892/lib/node_modules/@shopware-pwa/cli/node_modules/gluegun/build/toolbox/patching-tools.js:91:39)
    at step (/Users/thomasnohl/.npm/_npx/7892/lib/node_modules/@shopware-pwa/cli/node_modules/gluegun/build/toolbox/patching-tools.js:33:23)
    at Object.next (/Users/thomasnohl/.npm/_npx/7892/lib/node_modules/@shopware-pwa/cli/node_modules/gluegun/build/toolbox/patching-tools.js:14:53)
    at fulfilled (/Users/thomasnohl/.npm/_npx/7892/lib/node_modules/@shopware-pwa/cli/node_modules/gluegun/build/toolbox/patching-tools.js:5:58)
```

**Comment by joelschwegmann** [comment] 2020-10-07 10:16
Can you show me your Node and NPM/NPX Versions?

**Comment by thmsnhl** [comment] 2020-10-07 10:37
NPM Version: 6.14.8
Node Version 14.12.0

**Comment by joelschwegmann** [comment] 2020-10-07 10:42
All right you have to downgrade your Node version because Shopware PWA does not yet support the latest versions.
The version I am using and that works is **v12.17.3**.

**Comment by thmsnhl** [comment] 2020-10-07 11:21
Thank you for your input, I just tried to use 12.17.0 (12.17.3 does not exist) and also 12.14.0, 12.16.3.
All of the versions share the same result. If I go lower than v12.X I cannot run the command at all.

**Comment by joelschwegmann** [comment] 2020-10-07 11:31
Hmm, i will give you my installation doc. I hope it works then.
[https://joelruizcabrera.de/download/shopware-pwa-installation/](https://joelruizcabrera.de/download/shopware-pwa-installation/)

If you have some other questions then join the Shopware PWA Slack Channel :)
[https://join.slack.com/t/vuestorefront/shared_invite/zt-c4pw3ly8-r8GFYUCtTiOQU82yVKTK1w](https://join.slack.com/t/vuestorefront/shared_invite/zt-c4pw3ly8-r8GFYUCtTiOQU82yVKTK1w)

**Comment by thmsnhl** [comment] 2020-10-07 11:46
Thank you, I will have a look 🙏

**Comment by joelschwegmann** [comment] 2020-10-07 12:29
Does it work? :D

**Comment by thmsnhl** [comment] 2020-10-07 12:46
Sadly it doesn't. 😔 

I did however manage to get a little further in the process by a mix of 
* running `npx @shopware-pwa/cli init` again 
* fiddling in the nuxt.config.js 
* running `npx @shopware-pwa/cli init` another time
* running `shopware-pwa dev`

Now, since nuxt client side seems to build successfully, I am facing some issues with nuxt server side. 

I will update this thread if I find a solution 🤞

**Comment by thmsnhl** [comment] 2020-10-07 13:24
Okay, I give up 🤷 

I just tried everything in a new directory from ground up now without passing `init` to the `npx` command - this works fine. 
Afterwards I run `shopware-pwa init` this fails again, but the error output is slightly different: 

```bash
Preparing Nuxt project/Users/thomasnohl/Projekte/shopware-pwa/node_modules/gluegun/build/index.js:13
    throw up;
    ^

Error: Command failed: npx --ignore-existing create-nuxt-app@3.2.0 --answers "{\"name\":\"shopware-pwa-project\",\"description\":\"shopware-pwa-project description\",\"author\":\"Vue Storefront\",\"pm\":\"yarn\",\"ui\":\"none\",\"language\":\"js\",\"server\":\"none\",\"features\":[\"axios\",\"pwa\"],\"linter\":[\"prettier\",\"lintStaged\"],\"test\":\"jest\",\"mode\":\"universal\",\"target\":\"server\",\"devTools\":[],\"gitUsername\":\"\"}"
Trace: { ReferenceError: ejs:18
    16|     prefix-development: chore
    17|     include: scope
 >> 18| <%_ if (ci === 'github-actions') { _%>
    19| # Fetch and update latest `github-actions` pkgs
    20| - package-ecosystem: github-actions
    21|   directory: '/'

ci is not defined
    at eval (eval at compile (/Users/thomasnohl/.npm/_npx/13296/lib/node_modules/create-nuxt-app/node_modules/ejs/lib/ejs.js:652:12), <anonymous>:18:8)
    at Object.anonymous [as fn] (/Users/thomasnohl/.npm/_npx/13296/lib/node_modules/create-nuxt-app/node_modules/ejs/lib/ejs.js:682:17)
    at Transformer.render (/Users/thomasnohl/.npm/_npx/13296/lib/node_modules/create-nuxt-app/node_modules/jstransformer/index.js:289:25)
    at fileList.forEach.relativePath (/Users/thomasnohl/.npm/_npx/13296/lib/node_modules/create-nuxt-app/node_modules/sao/lib/runActions.js:69:27)
    at Array.forEach (<anonymous>)
    at stream.use (/Users/thomasnohl/.npm/_npx/13296/lib/node_modules/create-nuxt-app/node_modules/sao/lib/runActions.js:61:20)
    at current.then (/Users/thomasnohl/.npm/_npx/13296/lib/node_modules/create-nuxt-app/node_modules/majo/dist/majo.cjs.js:58:49) path: '' }
    at sao.run.catch (/Users/thomasnohl/.npm/_npx/13296/lib/node_modules/create-nuxt-app/lib/cli.js:51:17)

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:607:12)
```

If I read this correctly, there is an issue with the defaults that are set with the CLI-script when running `create-nuxt-app` 

I cannot put any more time into this 🙁

**Comment by joelschwegmann** [comment] 2020-10-07 13:31
Did you activated and installed the SwagShopwarePwa plugin to your Shopware 6 system?

**Comment by thmsnhl** [comment] 2020-10-08 06:29
No I didn't. There was no reason for me to go on with the plugin installation without completing the Shopware-pwa initialization on my machine 🤷‍♂️

**Comment by joelschwegmann** [comment] 2020-10-08 06:32
Could you join the Slack channel i'll wrote down in the comments? Then we can find the issue faster and we can chat in german :D

**Comment by patzick** [comment] 2020-10-08 17:39
@thmsnhl @joelschwegmann, unfortunately, the problem is with `create-nuxt-app`, it is fixed now in canary version, please use `npx @shopware-pwa/cli@canary init` and it should work!
Please let me know if that helps!

**Comment by thmsnhl** [comment] 2020-10-09 05:56
@patzick thanks for reaching out! 

I just tested `npx @shopware-pwa/cli@canary init` once with `canary`-option and once with `stable`-option and both of them fail with the good old `Cannot set property 'lint' of undefined` issue.

```bash
➜ projectfolder npx @shopware-pwa/cli@canary init
✔ Shopware instance address: · https://pwa-demo-api.shopware.com
✔ Shopware instance access token: · SWSC40-LJTNO6COUEN7CJMXKLA
✔ Which version you'd like to use: · latest stable (recommended)
✔ Preparing Nuxt project
⠙ Updating configuration for option: latest stable (recommended)/Users/thomasnohl/.npm/_npx/39718/lib/node_modules/@shopware-pwa/cli/node_modules/gluegun/build/index.js:13
    throw up;
    ^

TypeError: Cannot set property 'lint' of undefined
    at /Users/thomasnohl/.npm/_npx/39718/lib/node_modules/@shopware-pwa/cli/build/extensions/nuxt-extension.js:160:45
    at Object.<anonymous> (/Users/thomasnohl/.npm/_npx/39718/lib/node_modules/@shopware-pwa/cli/node_modules/gluegun/build/toolbox/patching-tools.js:91:39)
    at step (/Users/thomasnohl/.npm/_npx/39718/lib/node_modules/@shopware-pwa/cli/node_modules/gluegun/build/toolbox/patching-tools.js:33:23)
    at Object.next (/Users/thomasnohl/.npm/_npx/39718/lib/node_modules/@shopware-pwa/cli/node_modules/gluegun/build/toolbox/patching-tools.js:14:53)
    at fulfilled (/Users/thomasnohl/.npm/_npx/39718/lib/node_modules/@shopware-pwa/cli/node_modules/gluegun/build/toolbox/patching-tools.js:5:58)
```

**Comment by patzick** [comment] 2020-10-09 09:24
hey @thmsnhl, please reach me on slack, we'll check it out as I just tried that and worked. My guess would be you're using Node 14 instead of 12 :)

**Comment by joelschwegmann** [comment] 2020-10-09 09:27
version 12 does not seem to work for him

**Comment by joelschwegmann** [comment] 2020-10-09 09:28
@patzick 
Meanwhile version 12.17.0 doesn't work for me either. Also in Canary

**Comment by patzick** [comment] 2020-10-09 10:23
@joelschwegmann @thmsnhl thank you, folks, for help with that!
#1169 will close that issue, so after that wait a few minutes for the canary to be published and please try again 👍 

Canary is changing the structure a bit, so please choose `canary` on init as well :)
Please let me know if there will be still problems. We'll backport this fix into the stable version of the CLI as well after confirmation that everything works!

**Closed** 2020-10-09 10:28 UTC
Labels: bug

**Comment by thmsnhl** [comment] 2020-10-13 07:39
I'm sorry, that I couldn't respond earlier, I had other projects with higher priority. 

@patzick thank you for fixing this, I just tested the latest release and it seems to be working perfectly fine 🙏
