### ISSUE TITLE
[FEATURE] I want to change the customer data on the checkout

### ISSUE THREAD

**Issue by mkucmus** [DivanteLtd/shopware-pwa#376] opened 2020-02-11 19:15 UTC
**Describe how this feature will help us improve**

All the forms should be editable, and such actions should be synchronized with the backend. 
For not logged users we better have #375 done before. 

**Acceptance criteria**

- [ ] validations are plugged into all the editable fields
- [ ] checkout changes should go through only one service/hook
- [ ] code is 100% covered by tests

**Comment by patzick** [comment] 2020-02-14 08:03
Duplicate of #350

**Closed by patzick** 2020-02-14 08:03 UTC
Labels: Checkout
