### ISSUE TITLE
[FEATURE] Implement SearchCriteria builder for page resolver

### ISSUE THREAD

**Issue by mkucmus** [DivanteLtd/shopware-pwa#358] opened 2020-02-05 08:44 UTC
**Describe how this feature will help us improve**

Mechanism should convert SearchCriteria into GET query params.
Should behave just like native storefront in Shopware does. 

**Is your proposal related to a problem?**

**Describe the solution you'd considered**

**Acceptance criteria**

- []

**Comment by patzick** [comment] 2020-06-19 11:18
duplicate of #568

**Closed by patzick** 2020-06-19 11:18 UTC
Labels: Category Page, ideas
