### ISSUE TITLE
[API client] Basic search of products by query

### ISSUE THREAD

**Issue by patzick** [DivanteLtd/shopware-pwa#465] opened 2020-03-09 09:03 UTC
## Acceptance criteria
- [x] discover how to search on API
- [x] extend API client to add the ability of search

**Comment by rmakara** [comment] 2020-03-11 10:04
Is it a duplicate of https://github.com/DivanteLtd/shopware-pwa/issues/207 ?

**Closed** 2020-03-13 07:29 UTC
Labels: Core Team
